name: ci

on:
  push:
    branches-ignore:
      - gh-pages
      - 'renovate/**'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: pnpm/action-setup@v6.1.0

      - name: Setup node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 'lts/*'
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run tsc

      - run: pnpm run format:check

      - run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: pnpm/action-setup@v6.1.0

      - name: Setup node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 'lts/*'
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: pnpm/action-setup@v6.1.0

      - name: Setup node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 'lts/*'
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build
